name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "benchmarks/**"
      - "examples/**"
      - ".github/**"
      - "README.rst"
  release:
    types: [published]

jobs:
  lint:
    name: Lint and ruff code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build msgspec and install dependencies
        run: |
          pip install -e ".[dev]"

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: mypy
        run: pytest tests/test_mypy.py

      - name: pyright
        run: pytest tests/test_pyright.py

      - name: doctests
        run: pytest --doctest-modules msgspec

      - name: Rebuild with sanitizers & coverage
        env:
          MSGSPEC_SANITIZE: "true"
          MSGSPEC_COVERAGE: "true"
        run: |
          python setup.py clean --all
          # I know this is deprecated, but I can't find a way to keep the build
          # directory around anymore on new versions of setuptools
          python setup.py develop

      - name: Run tests with sanitizers
        env:
          PYTHONMALLOC: "malloc"
          ASAN_OPTIONS: "detect_leaks=0"
        run: |
          LD_PRELOAD=`gcc -print-file-name=libasan.so` coverage run -m pytest -s -m "not mypy and not pyright"

      - name: Generate coverage files
        run: |
          coverage xml
          gcov -abcu `find build/ -name *.o`

      - name: Upload Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml,_core.c.gcov,atof.h.gcov,ryu.h.gcov

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04-arm
          archs: aarch64
        - os: ubuntu-latest
          archs: x86_64
        - os: macos-latest
          archs: arm64
        - os: macos-15-intel
          archs: x86_64
        - os: windows-latest
          archs: AMD64
    env:
      CIBW_TEST_EXTRAS: "test"
      CIBW_TEST_COMMAND: "pytest {project}/tests"
      CIBW_BUILD: "cp311-* cp312-* cp313-*"
      CIBW_SKIP: "*-win32 *_i686 *_s390x *_ppc64le"
      CIBW_ARCHS: "${{ matrix.archs }}"
      CIBW_TEST_SKIP: "*_arm64 *-musllinux_*"
      CIBW_ENVIRONMENT: "CFLAGS=-g0"

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Environment
        if: github.event_name != 'release'
        run: |
            echo "CIBW_SKIP=${CIBW_SKIP} *-musllinux_*" >> $GITHUB_ENV

      - name: Build & Test Wheels
        uses: pypa/cibuildwheel@v2.22.0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build Source Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build source distribution
        run: python setup.py sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist/*.tar.gz

#  upload_pypi:
#    needs: [build_wheels, build_sdist]
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#    if: github.event_name == 'release' && github.event.action == 'published'
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          merge-multiple: true
#          path: dist
#          pattern: artifact-*
#
#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
